"""IBM Z (s390x) platform variant constraint values."""

package(
    default_visibility = ["//visibility:public"],
)

# IBM Z variants
constraint_value(
    name = "z13",
    constraint_setting = "//img/constraints:variant",
)

constraint_value(
    name = "z14",
    constraint_setting = "//img/constraints:variant",
)

constraint_value(
    name = "z15",
    constraint_setting = "//img/constraints:variant",
)

constraint_value(
    name = "z16",
    constraint_setting = "//img/constraints:variant",
)

filegroup(
    name = "all_files",
    srcs = glob(["**"]),
    visibility = ["//img/private/release:__subpackages__"],
)
